spring:
  datasource:
    url: jdbc:postgresql://ec2-50-17-194-186.compute-1.amazonaws.com:5432/d189o272lkjark?ssl=true&sslfactory=org.postgresql.ssl.NonValidatingFactory
    username: pfwzgkulzvvouw
    password: c04a0d165e33d86b045564c19d259f42b41320c690af278f1e3519a1044d4aed
    platform: postgres

    hikari:
      maximum-pool-size: 5
    jpa:
      hibernate:
        ddl-auto: update
        naming-strategy: org.hibernate.cfg.DefaultNamingStrategy
        connection:
          provider_disables_autocommit: true
      properties:
        hibernate:
          format_sql: true